volumes:
  steam-cache:
    name: steam-cache
    external: true
  gmod-cache:
    name: gmod-cache
    external: true
  lua-folder:
    driver: local
    driver_opts:
      type: none
      device: "${PWD}/lua"
      o: bind,rw
  cfg-folder:
    driver: local
    driver_opts:
      type: none
      device: "${PWD}/cfg"
      o: bind,rw
  maps-folder:
    driver: local
    driver_opts:
      type: none
      device: "${PWD}/maps"
      o: bind,rw
  addons-folder:
    driver: local
    driver_opts:
      type: none
      device: "${PWD}/addons"
      o: bind,rw
  data-folder:
    driver: local
    driver_opts:
      type: none
      device: "${PWD}/data"
      o: bind,rw
  gamemodes-folder:
    driver: local
    driver_opts:
      type: none
      device: "${PWD}/data"
      o: bind,rw

services:

  mariadb:
    container_name: dbg_db
    image: mariadb:lts
    volumes:
      - ./docker/data.local/mysql:/var/lib/mysql
    ports:
      - 127.0.0.1:${GMOD_MYSQL_PORT}:3306
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_DATABASE: ${GMOD_MYSQL_DB}
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '--silent']
      interval: 2s
      retries: 15

  fastdl:
    container_name: dbg_fastdl
    image: nginx:alpine
    restart: always
    volumes:
      - ./content:/var/www/html:z,ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:z,ro
    ports:
      - 80:80
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 20s

  redis:
    container_name: dbg_redis
    image: redis
    volumes:
      - ./docker/data.local/redis:/data
    ports:
      - 127.0.0.1:${GMOD_REDIS_PORT}:6379
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 1s
      timeout: 10s
      retries: 30

  gameserver:
    container_name: dbg_game
    image: ghcr.io/8char/gdev:latest
    build: .
    volumes:
      - steam-cache:/home/container/steam_cache
      - gmod-cache:/home/container/garrysmod/cache
      - lua-folder:/home/container/garrysmod/lua
      - cfg-folder:/home/container/garrysmod/cfg
      - maps-folder:/home/container/garrysmod/maps
      - addons-folder:/home/container/garrysmod/addons
      - data-folder:/home/container/garrysmod/data
      - gamemodes-folder:/home/container/garrysmod/data
    ports:
      - '${GMOD_PORT}:${GMOD_PORT}/tcp'
      - '${GMOD_PORT}:${GMOD_PORT}/udp'
    env_file: .env
    stdin_open: true
    tty: true
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy